#+TITLE:Recycling encouragement web-app
#+AUTHOR: Team gitignored

* Description
# non-technical person should be able to understand the project after reading this 

Our web app aims to promote a recycling habit among people. Users create accounts & can bring recyclable waste/ materials to a nearby recycling station. There, an operator will record it digitally & add reward points to the user's account. Users can exchange these reward points for recycled products such as notebooks, dustbins, manure etc. 

These products are recycled by workers at the recycling station. Each product is worth some amount of reward points based on its perceived value & can be sold for real money to generate revenue for the station as well. 

* Tech Stack
- HTML + CSS for the front-end
- PHP for the back-end 
  + handling registration, login, recording recycles, managing reward points
- SQLite as single-file RDBMS

* Features 
# techincal; what users can do
Users can: 

- regiter & login
- view reward points & rewards they can currently afford to exchange
- view nearby recycle stations

Recycle station operators can:

- log/ record recycles for data-keeping
- add reward points when recycled & deduct when redeemed
/Account registration for station operators have to be manually verified by developers/

* Novelty: What makes our project unique
- The reward point system is meant to gamify the recycling process. Users are provided return value in the form of tangible, useful products & thus, will want to recycle more.

- Special events can also be held to further boost user engagement. One such example would be to host competition where users have to recycle a minimum amount in order to participate. Random users are then selected to give prizes to. 

- Employment opportunities for involved personnel (operators, workers that make recycled products, waste collectors)
- Collected data can be aggregated & analysed to gain insight regarding wastage amount, recycling habits. Historical data can also be used to gague impacts of awareness campaigns, workshops on recycling trends.

* Contribution guide
1. Clone this repo
2. Create a branch with your own name
3. **Only make changes to your branch. Never to ~main~**
4. Don't merge to ~main~
5. Make pull requests(PRs) to main through the github website or a GUI tool instead
6. Notify team leader of new PRs
7. Don't merge PRs on your own

* Style guide
1. names for variables, ids, classes, functions, ... should be in ~camelCase~
